---
apiVersion: v1
kind: ConfigMap
metadata:
  name: action
  namespace: elk
data:
  action.yml: |
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 3 days , for service-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: elk
data:
  config.yml: |
    client:
      hosts:
        - 10.233.8.228
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: elk
  labels:
    app: curator
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curator
              image: bobrik/curator:5.7.6
              args: ["--config", "/etc/curator/config.yml","/etc/curator/action.yml"]
              volumeMounts:
                - mountPath: "/etc/curator/action.yml"
                  name: action
                  subPath: action.yml
                - mountPath: "/etc/curator/config.yml"
                  name: config
                  subPath: config.yml
          restartPolicy: OnFailure
          volumes:
            - name: action
              configMap:
                name: action
                defaultMode: 0777
            - name: config
              configMap:
                name: config
                defaultMode: 0777