# 简单
kind: Service
apiVersion: v1
metadata:
  name: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - port: 80 
      targetPort: 5000
      nodePort: 32767

---
# 复杂

kind: Service
apiVersion: v1
metadata:
  name: wuhan-jenkinsx-agent
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/proxy-body-size: 500m"
  labels:
    app: jenkins
    chart: jenkins-0.10.31
    component: jenkins-x-jenkins-master
    jenkins.io/chart-release: jenkins-x
    jenkins.io/version: 0.0.2902
  namespace: jx
spec:
  type: NodePort
  selector:
    component: jenkins-x-jenkins-master
  ports:
    - port: 50000 
      targetPort: 50000
      nodePort: 50000
      name: slavelistener